[package]
name = "perfetto-everywhere-collector"
description = "Perfetto protobuf collector for perfetto-everywhere browser traces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[dependencies]
perfetto-everywhere-core.workspace = true
