[package]
name = "perfetto-everywhere-collector"
description = "Perfetto protobuf collector for perfetto-everywhere browser traces"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "../../README.md"
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
perfetto-everywhere-core.workspace = true
perfetto-everywhere-web.workspace = true
prost = "=0.14.1"
tracing-perfetto-sdk-schema = "=0.13.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "=0.2.121"
